### PR TITLE
Explicit disposal of disposables

### PR DESCRIPTION
**Pull request by jnyrup**
I found some disposable objects that aren't explicitly disposed and I couldn't see why these shouldn't/couldn't.

### CODE REVIEW

**Comment by MarcinZiabek** [comment]
Hmm, that's strange, I was pretty sure that Resharper has proper warning for not disposing an IDisposable object 🤣 I understand that some objects (e.g. HttpClient) do not require disposing. However, I agree with at least some of your suggestions and therefore I am expecting such warnings in my code.

**Comment by jnyrup** [comment]
I think it's close to impossible for an automated tool to know if an object is _properly_ disposed.
I used [IDisposableAnalyzers](https://www.nuget.org/packages/IDisposableAnalyzers/) to catch these ones.
It had a bunch of warnings for for constructing skia objects, that I could not verify whether were false positives or not.

I started up the Previewer and Previewer.Examples to try to verify the changes (very pleasant experience).
Nothing seemed broken for me, but it was getting late for me, so I didn't get to verify them all.
I'll see if I can find time to more closely verify the changes.

And you're very welcome, I like to help out where I can.

**Comment by MarcinZiabek** [comment]
> I think it's close to impossible for an automated tool to know if an object is properly disposed.

You are right, in general, this could be equivalent to the halting problem. However, in cases like you have detected, this should be straightforward and produce at least a warning. I would say that this inspection existed in Resharper but maybe I am mistaken.

> I used [IDisposableAnalyzers](https://www.nuget.org/packages/IDisposableAnalyzers/) to catch these ones.
> It had a bunch of warnings for for constructing skia objects, that I could not verify whether were false positives or not.

Would you like to share more insights about the tools that you are using to validate code quality?

> I started up the Previewer and Previewer.Examples to try to verify the changes (very pleasant experience).
> Nothing seemed broken for me, but it was getting late for me, so I didn't get to verify them all.
> I'll see if I can find time to more closely verify the changes.

That's ok, I am more than happy to test everything 😁 I wanted to estimate how much time should I spend investigating code and testing the application. 

Either way, I am planning to go through all your suggestions, one by one, and compare them to the official documentation. Honestly, in most cases, I just made stupid mistakes. On the other hand, I would like to read what happens when you dispose a started and not finished Thread. This is a great knowledge validation and learning opportunity!

Have a great day

**Comment by jnyrup** [comment]
> Would you like to share more insights about the tools that you are using to validate code quality?

I have a list of analyzers that I sometimes enable for projects to see if they can spot anything.
* `IDisposableAnalyzers`
* `Microsoft.VisualStudio.Threading.Analyzers`
* `AsyncFixer`
* `Meziantou.Analyzer`
* `Roslynator.Analyzers`
* `Asyncify`
* `Lindhart.Analyser.MissingAwaitWarning`

Some other tools I use:
* Code Coverage
* Mutation testing - https://github.com/stryker-mutator/stryker-net/
* Snapshot testing  - e.g. comparing changes of public API
* Fuzz testing - https://github.com/Metalnem/sharpfuzz

**Comment by MarcinZiabek** [comment]
Thank you! As Resharper plays an important role in my workflow, I haven't got an occasion to investigate Roslyn analysers. I certainly should! 😁 I am also pretty familiar with most of the tools on your list, but the Fuzz testing sounds relatively new and exciting - I will do my best to read about it and check if it can help in QuestPDF development.

**Comment by MarcinZiabek** [comment]
I have merged your changes into the 2022.5 release branch. Thank you for your help! I appreciate it ❤️

**Comment by jnyrup** [comment]
You're welcome!
Happy to help.

**Pull request merged**
