### PR TITLE
Add drop shadow option to text

### PR DESCRIPTION
**Pull request by flostellbrink**
Thanks for this great library!

Was missing text shadows, so I went ahead and added them.
Not sure if this is a feature you're looking for, but just in case.

I tried adding an example, but ran into: #334

Was also trying to figure out inner shadows/glow. But couldn't quite figure that out yet.
Would appreciate any pointers in the right direction :)

### CODE REVIEW

**Comment by flostellbrink** [comment]
Would you be interested in merging this @MarcinZiabek 
Just so I know whether to update or close the PR :)

**Comment by MarcinZiabek** [comment]
Honestly, I am not sure... I would love to know if this feature is useful for others.

Have you investigated if the drop shadow is saved as vector graphics or as an image layer? If this effect is rasterized, maybe it should not be included.

**Comment by flostellbrink** [comment]
Great point, it does rasterize the shadow and the text itself.
Gonna close this :)

**Comment by MarcinZiabek** [comment]
@flostellbrink Either way, let me thank you for preparing this PR and apologize for my late response 🥰

**Comment by MarcinZiabek** [comment]
@flostellbrink Offtopic: would you like to take a look at this PR and provide your thoughts? https://github.com/QuestPDF/QuestPDF/pull/357 Much appreciated!

**Pull request closed without merging**
