### PR TITLE
Code quality improvement in TextStyleManager

### PR DESCRIPTION
**Pull request by y0ung3r**
### Changes
- **Added `GetValue` and `SetValue` methods to `TextStyle` to get property value using `TextStyleProperty`**

- **Added `StylesApplyingOptions` record to store `OverrideStyle`, `OverrideFontFamily` and `AllowFallback` properties**
Before
image
After
image

- **Simplified `MutateStyle` method**
Before
image
After
image

- **Simplified `ApplyStyleProperties` method**
Before
image
After
image

### CODE REVIEW

**Comment by MarcinZiabek** [comment]
Thank you so much for investigating the code and providing this improvement. I highly appreciate your help.

This area of the library is quite interesting. At the beginning of the development process, the idea of an immutable TextStyle object was introduced. Consequently, according to functional programming, performing any change instantiates a new object. In specific FluentAPI chains, this may result in multiple TextStyle objects per Text element. As a result, it is very taxing on the garbage collector.

This code was designed to mitigate the creation of new TextStyle instances by tracking the type of change and looking for potentially already existing class instances. To make the code even faster, multi-level caches were introduced.

Still, we need to be careful. Introducing reflection may significantly reduce performance (especially in multi-threaded scenarios) by increasing the GC load. Making proper tests may help with decision-making.

**Comment by MarcinZiabek** [comment]
@y0ung3r Would you mind me keeping this PR open? :) I am seriously considering merging it; just need to find time to benchmark all changes and ensure it does not impact performance.

**Comment by y0ung3r** [comment]
@MarcinZiabek I apologize! It's not your fault. I wanted to do all the necessary benchmarks myself, but I don't have enough time. So I decided not to bother you with a draft version.

Sure, keep the PR open. I will be only glad if you can do all the necessary tests faster than me

**Comment by y0ung3r** [comment]
Instead of benchmarks, I tried creating a different object model for the TextStyle properties. However, I ran into several problems that I couldn't solve. 

The root of all the evils of this code section is that MutateStyle takes object as a parameter. My idea was to represent a property, its value and type as a single object.

Anyway, I spent time trying to create something more worthwhile, but in the end there was no time left for anything else. This is the reason why I closed the PR

**Comment by MarcinZiabek** [comment]
No worries! 

I think that your concept is excellent and could easily be the next iteration of the TextStyle handling logic. However, as it is a library hot-path, some performance testing is required. In theory, your changes should not affect performance thanks to sophisticated cache usage. I am happy to perform the necessary measurements at some point once other high-priority tasks are done.

I am eager to learn more about your alternative concept of the object model. Would you please elaborate a little bit more?

**Comment by y0ung3r** [comment]
@MarcinZiabek Hello!
I created a separate branch in my fork to demonstrate the alternative concept.
Please check this pull request: https://github.com/y0ung3r/QuestPDF/pull/1

**Comment by MarcinZiabek** [comment]
Hey :)

I have waited a little to accomplish huge enough progress in this effort first: https://github.com/QuestPDF/QuestPDF/discussions/622. It allows me to redesign many areas related to text rendering, including the way how TextStyle is handled.

I have used your approach (using reflection to mutate the TextStyle object) with a new concept of assigning IDs to each TextStyle. While your enhancement makes the code significantly shorter, mine allows you to remove hash-calculation and dramatically reduces the resolving process.

Would you please take a look at my changes and share your opinion? https://github.com/QuestPDF/QuestPDF/commit/b2d9815bda625d721f5e4e900c6464e62763d54f

**Comment by y0ung3r** [comment]
@MarcinZiabek I am very happy that you maximized my ideas in the new implementation.

I think this is a great basis for future refactoring. For example, it would be great to get rid of reflection and make values strictly typed instead of using `object`.

Does that mean we can close this PR?

**Comment by y0ung3r** [comment]
@MarcinZiabek Hi!

I think that this PR is no longer needed.
I'm glad that you used my work. Thanks!

**Pull request closed without merging**
