### PR TITLE
Reduce size of TextStyle and use strings to cache them in the render stage

### PR DESCRIPTION
**Pull request by maartenba**
Reduces the size of TextStyle to reduce memory footprint in the table benchmark. Also speeds up GC by moving the cache key calculation into the render stage, and using simple strings instead of the `ValueTuple` that was originally created.

### CODE REVIEW

**Comment by jnyrup** [comment]
Another approach to handle hash collisions, could be to construct the dictionaries with custom `IEqualityComparer`s.
That also allows making the `valueFactory` argument static.
See https://github.com/jnyrup/QuestPDF/commit/d25233386fd9191bb7de5918e73cbad34f92c310.

(I haven't been able to run the benchmarks to compare the performance of this approach)

**Comment by MarcinZiabek** [comment]
My current plan is to follow our initial idea, by creating TextStyleManager and tracking all mutations performed on TextStyle objects. This should nicely reduce number of allocations by several orders of magnitude. Then, the dictionary can use simple reference comparison. This of course requires some time to prepare and handle all potential corner cases. However, you have found a huge bottlenectk worh the improvements 😁

**Comment by MarcinZiabek** [comment]
In the 2022.9 release (still WIP), I have solved the GC cost related to TextStyle allocation. https://github.com/QuestPDF/QuestPDF/pull/341

**Comment by maartenba** [comment]
That's awesome!

**Pull request closed without merging**
