### PR TITLE
WIP - Implement font fallback

### PR DESCRIPTION
**Pull request by Bebo-Maker**
This PR implements font fallback, which is possible with the use of the `SKFontManager.MatchCharacter` method.

Im already getting pretty good results

| Before | After |
| --- | ---  |
| Before| After |

### CODE REVIEW

**Comment by Bebo-Maker** [comment]
The algorithm which splits up the text into individual segments (`FontFallback.BuildRuns()` and `FontFallback.BuildTypefaces()`) still needs some work. 
Im sure there is a more clever and efficient way to do it. Any suggestions on how to improve it?

**Comment by MarcinZiabek** [comment]
This is a rather impressive implementation. I am excited about it! Thank you for giving it a try 😁

My thoughts:
1) The font fallback operation happens in the `SkiaCanvasBase.DrawText` method only. Therefore, the algorithm is applied only during the text rendering process and NOT during text measurement. The alternative font may have different metrics (glyph width), the resulting text may take significantly less or more space, and therefore produce visual artifacts. I assume we want to perform this operation during both: measurement and drawing operations.
2) Introducing font fallback significantly increases time complexity. Previously `O(N)` in all cases, now `O(N)` in the average case and `O(N*M)` in the worst case, where `N` - length of text, `M` - number of fonts available. Of course, even the average complexity gets worse as we need to check the presence of each glyph. I am not sure how much impact it has.
3) This thought is a combination of previous points. We perform font fallback in both measurement and drawing operations, and also the font fallback operation impacts performance. Possibly, we can combine it with the existing caching mechanism. In most documents, drawing text is one of the most computationally intensive steps.
4) Font fallback works great and helps with the development process. However, it may also introduce confusion. Scenario: on the development machine, the target font A is present. However, in the production environment, font A is not available and is replaced by another font B automatically. This changes how the document looks or even produces infinite layout exceptions in more constrained cases. The developer thinks it is a library bug, rather than recognizing the font fallback functionality. Font fallback is great in web development, when we want to display the page as correctly as possible, I am not sure about the PDF generation domain.

Again, I am not criticizing your idea / implementation. I love the overall result. I want to assess all pros and cons 😁

**Comment by Bebo-Maker** [comment]
> 1 - 3.

Yes, you are correct. I realized this yesterday night, we need to measure with the fallback fonts as well. Otherwise its possible that we screw up text measuring if the fallback typeface significantly changes size/layout.

The main problem im not sure how to solve is this:
We could split up the text before measuring and get the normal and fallback runs used to measure. However:
The fallback mechanism returns `SKTypeface` and we would need to find some way to modify the `TextStyle` to use the specified `SKTypeface` again. I hope you get what im trying to say? 😅

---

> 4. Font fallback works great and helps with the development process. However, it may also introduce confusion.

Implementing font fallback, i didnt think about this. Now im asking myself if implementing font fallback is even a good idea? 😅

**Comment by MarcinZiabek** [comment]
> Implementing font fallback, i didnt think about this. Now im asking myself if implementing font fallback is even a good idea? 

At this point, I am not really sure what to do with this feature. I love it, yet see certain drawbacks. It would be much easier to have entire team to discuss various perspectives. Library development is just challenging, especially once it starts to get attention 😁

However, I think that we can use your hard work to help reduce confusion. In the DEBUG mode, we can perform additional checks and detect if all used text characters exist in the assigned font. This way, if some glyphs are not present, we can let the developer know that something is wrong by throwing a meaningful exception.

On the other hand, in the RELEASE mode, we should avoid this additional step: 1) to not reduce performance, 2) to not block generating slightly incorrect but maybe still usable documents.

What do you think about it?

**Comment by Bebo-Maker** [comment]
Your idea sounds great. 
I agree with your initial thought, that font fallback is probably not the best idea to implement.
I assume by DEBUG mode you mean checking if a debugger is attached (`(System.Diagnostics.Debugger.IsAttached`)?
Similar to how its done for `DebuggingProxy`?
I believe the implementation of this (Checking for missing characters and throwing an exception) would be pretty straight forward and doesnt add the unnecessary complexity added with this PR.

**Comment by MarcinZiabek** [comment]
> I assume by DEBUG mode you mean checking if a debugger is attached ((System.Diagnostics.Debugger.IsAttached)?
> Similar to how its done for DebuggingProxy?

Yes, I think so. I am not aware about any alternative way to check if the host is in the debug mode. The pre-processor directives `#If DEBUG` are connected to library build system, not to nuget consumer. 

> I believe the implementation of this (Checking for missing characters and throwing an exception) would be pretty straight forward and doesnt add the unnecessary complexity added with this PR.

Yup, it is just using your work in a slightly different manner. The hardest challenge is already solved: how to detect that glyph is not present in the given font 😁

**Comment by MarcinZiabek** [comment]
I am currently experimenting with your code. Let me say this: splitting the text into separate runs is very clever! I am hoping to perform this process a little bit earlier though. Instead of using the `TextRun` objects (from your prototype) and perform font-fallback checks when the text is rendered, I would like to do this when API objects are created, essentially creating separate `TextBlockSpan` elements for each custom font.

Also, I am thinking: maybe this feature should be opt-in? By default, let's throw an exception describing how to enable font fallback? Also, the `TextStyle` object should specify a list of fonts that should be considered. What do you think?

**Comment by Bebo-Maker** [comment]
That sounds great, im looking forward to your implementation. If i can help in any way, just let me know.

+1 on adding this as an opt-in feature. Are you planning to expose this flag in `Settings` (recently added i believe) or in `DocumentMetadata`?

**Comment by MarcinZiabek** [comment]
> +1 on adding this as an opt-in feature. Are you planning to expose this flag in `Settings` (recently added i believe) or in `DocumentMetadata`?

Yes, I think so. I am not sure yet about the exact API though.

Having only one control parameter in `DocumentMetadata` didn't present any issues. But over time, I added more, and we can only predict the future. I believe that this is simple yet important decision.

I still don't have much spare time, so I was looking for potential features that I can introduce in the upcoming release. And this way I reminded myself about your fantastic prototype. So once again, thank you for your contributions!

**Comment by Bebo-Maker** [comment]
@MarcinZiabek Looks good to me so far (i looked at the code, did not test it).
Unfortunately im in the process of moving and wont be able to test your code for a couple of days.

Suggestion: I think it would be better if you would use git PRs instead of 'only' using branches for new features. 
That way its easier for users to track progress of new features.
Also, other contributors can comment on new code and help to sort out bugs at the time of the implementation, rather then when it actually gets released.

**Comment by Bebo-Maker** [comment]
This feature is part of the 2022.9 Release, closing this. Great work Marcin.

**Pull request closed without merging**
